"""Stable enum-like reason codes for Invariant-E (execution admission only; not governance policy codes)."""

# Envelope / preconditions
IE_DENIED_INVALID_ENVELOPE = "IE_DENIED_INVALID_ENVELOPE"
IE_DENIED_GOVERNANCE_NOT_PASS = "IE_DENIED_GOVERNANCE_NOT_PASS"
IE_DENIED_MISSING_TRACE = "IE_DENIED_MISSING_TRACE"
IE_DENIED_MISSING_PLAN_HASH = "IE_DENIED_MISSING_PLAN_HASH"
IE_DENIED_MISSING_SPEC_HASH = "IE_DENIED_MISSING_SPEC_HASH"
IE_DENIED_EMPTY_OPERATIONS = "IE_DENIED_EMPTY_OPERATIONS"

# AuthorityValid
IE_DENIED_IDENTITY_TENANT_MISMATCH = "IE_DENIED_IDENTITY_TENANT_MISMATCH"
IE_DENIED_PROD_APPROVAL_REQUIRED = "IE_DENIED_PROD_APPROVAL_REQUIRED"

# CapabilityBounded
IE_DENIED_CAPABILITY_NOT_ALLOWED = "IE_DENIED_CAPABILITY_NOT_ALLOWED"

# EconomicBounded
IE_DENIED_BUDGET_REQUIRED = "IE_DENIED_BUDGET_REQUIRED"

# SafetyBounded (defensive; gate should already block)
IE_DENIED_FORBIDDEN_OPERATION = "IE_DENIED_FORBIDDEN_OPERATION"

# Success
IE_ALLOWED = "IE_ALLOWED"
