"""Stable enum-like reason codes for UATO (admissibility only; not governance policy codes)."""

UATO_BLOCK_INVALID_INPUT = "UATO_BLOCK_INVALID_INPUT"
UATO_BLOCK_MALFORMED_PLAN = "UATO_BLOCK_MALFORMED_PLAN"
UATO_BLOCK_TENANT_MISMATCH = "UATO_BLOCK_TENANT_MISMATCH"
UATO_BLOCK_IDENTITY_NOT_BOUND = "UATO_BLOCK_IDENTITY_NOT_BOUND"
UATO_BLOCK_LOW_TRUST_LOW_AUTHORITY = "UATO_BLOCK_LOW_TRUST_LOW_AUTHORITY"

UATO_ESCALATE_LOW_TRUST_HIGH_AUTHORITY = "UATO_ESCALATE_LOW_TRUST_HIGH_AUTHORITY"
UATO_REQUIRE_APPROVAL_HIGH_TRUST_LOW_AUTHORITY = "UATO_REQUIRE_APPROVAL_HIGH_TRUST_LOW_AUTHORITY"
UATO_PASS_HIGH_TRUST_HIGH_AUTHORITY = "UATO_PASS_HIGH_TRUST_HIGH_AUTHORITY"
